// Code generated by MockGen. DO NOT EDIT.
// Source: ./webook/internal/service/sms/ratelimit/limiter.go
//
// Generated by this command:
//
//	mockgen -source=./webook/internal/service/sms/ratelimit/limiter.go -package=ratelimitmocks -destination=./webook/internal/service/sms/ratelimit/mocks/limiter.mock.go
//

// Package ratelimitmocks is a generated GoMock package.
package ratelimitmocks
